// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/aperturerobotics/objectenc/objectenc.proto

/*
Package objectenc is a generated protocol buffer package.

It is generated from these files:
	github.com/aperturerobotics/objectenc/objectenc.proto

It has these top-level messages:
	EncryptedBlob
*/
package objectenc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// EncryptionType is the object encryption type.
type EncryptionType int32

const (
	// EncryptionType_UNENCRYPTED is the unencrypted value.
	EncryptionType_EncryptionType_UNENCRYPTED EncryptionType = 0
	// EncryptionType_AES encrypts the data with an out-of-band hashed AES key.
	EncryptionType_EncryptionType_AES EncryptionType = 1
	// EncryptionType_SECRET_BOX encrypts the data with an out-of-band secretbox key and nonce.
	EncryptionType_EncryptionType_SECRET_BOX EncryptionType = 2
)

var EncryptionType_name = map[int32]string{
	0: "EncryptionType_UNENCRYPTED",
	1: "EncryptionType_AES",
	2: "EncryptionType_SECRET_BOX",
}
var EncryptionType_value = map[string]int32{
	"EncryptionType_UNENCRYPTED": 0,
	"EncryptionType_AES":         1,
	"EncryptionType_SECRET_BOX":  2,
}

func (x EncryptionType) String() string {
	return proto.EnumName(EncryptionType_name, int32(x))
}
func (EncryptionType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// CompressionType is the compression type used.
type CompressionType int32

const (
	// CompressionType_UNCOMPRESSED is the uncompressed mode.
	CompressionType_CompressionType_UNCOMPRESSED CompressionType = 0
	// CompressionType_SNAPPY indicates snappy compression.
	CompressionType_CompressionType_SNAPPY CompressionType = 1
)

var CompressionType_name = map[int32]string{
	0: "CompressionType_UNCOMPRESSED",
	1: "CompressionType_SNAPPY",
}
var CompressionType_value = map[string]int32{
	"CompressionType_UNCOMPRESSED": 0,
	"CompressionType_SNAPPY":       1,
}

func (x CompressionType) String() string {
	return proto.EnumName(CompressionType_name, int32(x))
}
func (CompressionType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// EncryptedBlob contains a potentially encrypted blob of data.
type EncryptedBlob struct {
	// EncryptionType is the encryption type in use.
	EncType EncryptionType `protobuf:"varint,1,opt,name=enc_type,json=encType,enum=objectenc.EncryptionType" json:"enc_type,omitempty"`
	// EncData contains the encrypted data.
	EncData []byte `protobuf:"bytes,2,opt,name=enc_data,json=encData,proto3" json:"enc_data,omitempty"`
	// EncMetadata contains any metadata required for decryption.
	EncMetadata []byte `protobuf:"bytes,3,opt,name=enc_metadata,json=encMetadata,proto3" json:"enc_metadata,omitempty"`
	// CompressionType is the compression type to use.
	CompressionType CompressionType `protobuf:"varint,4,opt,name=compression_type,json=compressionType,enum=objectenc.CompressionType" json:"compression_type,omitempty"`
}

func (m *EncryptedBlob) Reset()                    { *m = EncryptedBlob{} }
func (m *EncryptedBlob) String() string            { return proto.CompactTextString(m) }
func (*EncryptedBlob) ProtoMessage()               {}
func (*EncryptedBlob) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EncryptedBlob) GetEncType() EncryptionType {
	if m != nil {
		return m.EncType
	}
	return EncryptionType_EncryptionType_UNENCRYPTED
}

func (m *EncryptedBlob) GetEncData() []byte {
	if m != nil {
		return m.EncData
	}
	return nil
}

func (m *EncryptedBlob) GetEncMetadata() []byte {
	if m != nil {
		return m.EncMetadata
	}
	return nil
}

func (m *EncryptedBlob) GetCompressionType() CompressionType {
	if m != nil {
		return m.CompressionType
	}
	return CompressionType_CompressionType_UNCOMPRESSED
}

func init() {
	proto.RegisterType((*EncryptedBlob)(nil), "objectenc.EncryptedBlob")
	proto.RegisterEnum("objectenc.EncryptionType", EncryptionType_name, EncryptionType_value)
	proto.RegisterEnum("objectenc.CompressionType", CompressionType_name, CompressionType_value)
}

func init() {
	proto.RegisterFile("github.com/aperturerobotics/objectenc/objectenc.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xcb, 0x6e, 0xc2, 0x30,
	0x10, 0x45, 0x6b, 0x5a, 0xf5, 0x31, 0xa5, 0x10, 0x79, 0x81, 0x00, 0xb5, 0x15, 0xed, 0x0a, 0xb1,
	0x00, 0xa9, 0x8f, 0x0f, 0x80, 0xe0, 0x25, 0x21, 0x4a, 0x40, 0x2a, 0xab, 0xc8, 0x31, 0x23, 0x9a,
	0xaa, 0xd8, 0x96, 0x31, 0x8b, 0xfc, 0x62, 0xbf, 0xaa, 0xc2, 0xa0, 0xa6, 0xc9, 0x6e, 0x74, 0xee,
	0xb5, 0xcf, 0x48, 0x03, 0xef, 0x9b, 0xcc, 0x7e, 0xee, 0xd3, 0xa1, 0x50, 0xdb, 0x11, 0xd7, 0x68,
	0xec, 0xde, 0xa0, 0x51, 0xa9, 0xb2, 0x99, 0xd8, 0x8d, 0x54, 0xfa, 0x85, 0xc2, 0xa2, 0x14, 0xc5,
	0x34, 0xd4, 0x46, 0x59, 0x45, 0x6f, 0xfe, 0xc0, 0xf3, 0x0f, 0x81, 0x3b, 0x26, 0x85, 0xc9, 0xb5,
	0xc5, 0xf5, 0xe4, 0x5b, 0xa5, 0xf4, 0x0d, 0xae, 0x51, 0x8a, 0xc4, 0xe6, 0x1a, 0xdb, 0xa4, 0x47,
	0xfa, 0x8d, 0x97, 0xce, 0xb0, 0xf8, 0xe0, 0xd4, 0xcd, 0x94, 0x5c, 0xe4, 0x1a, 0xa3, 0x2b, 0x94,
	0xe2, 0x30, 0xd0, 0xce, 0xf1, 0xd5, 0x9a, 0x5b, 0xde, 0xae, 0xf5, 0x48, 0xbf, 0xee, 0xa2, 0x29,
	0xb7, 0x9c, 0x3e, 0x41, 0xfd, 0x10, 0x6d, 0xd1, 0x72, 0x17, 0x9f, 0xbb, 0xf8, 0x16, 0xa5, 0x98,
	0x9d, 0x10, 0x65, 0xe0, 0x09, 0xb5, 0xd5, 0x06, 0x77, 0xbb, 0x4c, 0xc9, 0xa3, 0xfb, 0xc2, 0xb9,
	0xbb, 0xff, 0xdc, 0x7e, 0x51, 0x71, 0xf2, 0xa6, 0x28, 0x83, 0xc1, 0x06, 0x1a, 0xe5, 0xfd, 0xe8,
	0x23, 0x74, 0xcb, 0x24, 0x59, 0x06, 0x2c, 0xf0, 0xa3, 0x55, 0xb8, 0x60, 0x53, 0xef, 0x8c, 0xb6,
	0x80, 0x56, 0xf2, 0x31, 0x8b, 0x3d, 0x42, 0x1f, 0xa0, 0x53, 0xe1, 0x31, 0xf3, 0x23, 0xb6, 0x48,
	0x26, 0xf3, 0x0f, 0xaf, 0x36, 0x98, 0x43, 0xb3, 0xb2, 0x0c, 0xed, 0xc1, 0x7d, 0x05, 0x25, 0xcb,
	0xc0, 0x9f, 0xcf, 0xc2, 0x88, 0xc5, 0xb1, 0x73, 0x75, 0xa1, 0x55, 0x6d, 0xc4, 0xc1, 0x38, 0x0c,
	0x57, 0x1e, 0x49, 0x2f, 0xdd, 0x61, 0x5e, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x49, 0xf6, 0x66,
	0xc1, 0xd1, 0x01, 0x00, 0x00,
}
